### ISSUE TITLE
NPM Module doesn't ship build folder

### ISSUE THREAD

**Issue by toddpi314** [madole/express-dev#1]
When attempting reference of your package in NodeJS, the package.json is referencing 

``` javascript
...
  "main": "build/index.js",
...
```

By default, `npm publish` will clone the existing `.gitignore` into the `.npmignore` used to package your module. Since folder `build` exists in the `.gitignore`, your build artifacts are not making it out to npm.

To mitigate, add a file `.npmignore` that is blank in your repo root and republish your package. 

This is a cool module and I would love to use it!

**Comment by madole** [comment]
Thanks for the heads up. I'll get that sorted today and republish. :)

**Comment by madole** [comment]
Sorted and deployed
